config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  get '/posts/:id/room', to: 'messages#index'
  # get '/posts/:id/room', to: 'posts#room'
  resources :posts do
    resources :reviews
    resources :messages, :only => [:create, :update, :destroy]
  end
  devise_scope :user do
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  end
  resources :users, :only => [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :post_users, dependent: :destroy
  has_many :users, through: :post_users
  belongs_to :user
end

app/models/post_user.rb
class PostUser < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :post_users, dependent: :destroy
  has_many :attended_posts, through: :post_users, source: :post
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  
  # 受講する
  def attend(post)
    attended_posts << post
  end

  # 受講を取りやめる
  def unfollow(other_user)
    attended_posts.find_by(user_id: other_user.id).destroy
  end

  # 現在のユーザーが受講していたらtrueを返す
  def attend?(post)
    attended_posts.include?(post)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!,except: [:index] ,if: :home_controller?

  def home_controller?
    self.controller_name == "home"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @user = current_user
      @posts = Post.includes(:user).all
      render 'posts/index'
    else
      render layout: false 
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @post = Post.find(params[:id])
    unless current_user.attend?(@post)
      current_user.attend(@post)
      flash[:notice] = "#{@post.title}を受講しました。"
    else
      @messages = Message.where(post_id: @post.id)
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:teacher_id, :student_id, :content, :image_url)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.include(:users).all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @user = User.find(@post.user_id)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @user, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_user
      @user = User.find(@post.user_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:id, :user_id, :title, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create

  end

  def update

  end

  def destroy

  end

  private

    def review_params
      
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for twitter
  def twitter
    callback_for(:twitter)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="top">
    <div class="top-bgimg absolute"></div>
    <div class="top-bgcover absolute animation"></div>
    <div class="delay-animation">
      <div class="absolute title">EDU.ROOM</div>
      <div class="absolute subTitle">「教えたい」と「教わりたい」を繋ぐ部屋。</div>
      
      <%= link_to new_user_session_path, class: "absolute button2" do %>
        <p class="clik">Sign in</p>
        <div class="hoveur"></div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '2842131749161059',
          cookie     : true,
          xfbml      : true,
          version    : 'v3.2'
        });
          
        FB.AppEvents.logPageView();   
          
      };
      
      FB.getLoginStatus(function(response) {
          statusChangeCallback(response);
      });

      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

      function checkLoginState() {
        FB.getLoginStatus(function(response) {
          statusChangeCallback(response);
        });
      }
    </script>
  </head>

  <body>
    <h1 class="eduroom"><%= link_to "EDU.ROOM", root_path %></h1>
    <hr>
    <div id="container">
      <ul id="menu">
        <li><a href="#">About Me</a>
          <ul>
            <li><a href="#">Lorem ipsum dolor</a></li>
            <li><a href="#">Maecenas lacinia sem</a></li>
            <li><a href="#">Suspendisse fringilla</a></li>
          </ul>
        </li>
        <li><a href="#">Portfolio</a>
          <ul>
            <li><a href="#">Lorem ipsum dolor</a></li>
            <li><a href="#">Maecenas dignissim fermentum luctus</a></li>
            <li><a href="#">Suspendisse fringilla</a></li>
            <li><a href="#">Lorem ipsum dolor</a></li>
            <li><a href="#">Maecenas lacinia sem</a></li>
            <li><a href="#">Suspendisse fringilla</a></li>
          </ul>
        </li>
        <li><a href="#">Clients</a>
          <ul>
            <li><a href="#">Lorem ipsum dolor</a></li>
            <li><a href="#">Maecenas lacinia sem</a></li>
            <li><a href="#">Suspendisse fringilla</a></li>
          </ul>
        </li>
        <li><a href="#">Contact Me</a>
          <ul>
            <li><a href="#">Lorem ipsum dolor</a></li>
            <li><a href="#">Maecenas dignissim fermentum luctus</a></li>
            <li><a href="#">Suspendisse fringilla</a></li>
          </ul>
        </li>
        <li><a href="#">Support</a></li>
      </ul>
      </div>
    <% if false %>
      <menu>
        <li class="subject"><a>科目</a></li>
        <li class="settings">
          <% if user_signed_in? %>
            <%= link_to  "マイページ", @user %>
            <%= link_to  "部屋を作る", new_post_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
        </li>
      </menu>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.number_field :teacher_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_area :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div>
  <h1><%= @post.title %></h1><h3>-<%= @post.description %>-</h3>
</div>

<div>
  <div>
    受講人数：<%= @post.users.count %>
  </div>
  <div>
    投稿数：<%= @post.messages.count %>
  </div>
</div>

<div>
</div>

<% @messages.each do |message| %>
  <%= image_tag message.image_url if message.image_url %>
  <%= message.content %>
<% end %>

<div class="form-btn" id="form-btn">FA</div>

<div class="modal-bg" id="modal-bg">
  <div class="modal">
    なんやいろいろ
  </div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @message.teacher_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @message.student_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @message.image_url %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/posts/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.text_field :title, required: true  %>
    <%= form.text_area :description, required: true, placeholder: '' %>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<ul class="bxslider">
  <% @posts.each_with_index do |post, i| %>
    <% if (i % 12) == 0 %>
      <div class="container">
    <% end %>
    <li>
      <div class="item">
        <%= link_to "", post, class: "item-link" %>
        <div class="tape tapeJ">科目</div>
        <div class="tape tapeT"><%= post.title.truncate(15) %></div>
        <div>講師ID：<%= post.user.id %></div>
        <div><%= post.description.truncate(15) %></div>
        <div>受講者数：<%= post.users.count %></div>
        <% if post.user != current_user %>
          <div class="other-link">
            <%= link_to "#{ current_user.attend?(post) ? "入室" : "受講" }する", "/posts/#{post.id}/room" %>
            <%= link_to "レビュー", new_post_review_path(post.id) %>
          </div>
        <% end %>
      </div>
    </li>
    <% if (i % 12) == 11 || @posts.count == i + 1 %>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div>
  <p><%= @post.title %></p>
  <p>講師ID：<%= @user.id %></p>
  <p><%= @post.description %></p>
</div>

<% if @post.user_id == current_user.id %>
  <%= link_to '編集する', edit_post_path(@post) %>
<% else %>
  <%= link_to  "教わりにいく", "#" %>
<% end %>

app/views/users/show.html.erb
<div>講師ID：<%= @user.id %></div>
<div>開設部屋数：<%= @posts.count %></div>
<div>
  <% @posts.each do |post| %>
    <div>
      <div><%= post.title %></div>
      <div><%= post.description %></div>
      <div>受講者数：<%= post.users.count %></div>
      <div>
        <% if @user != current_user %>
          <%= link_to  "受講する", "/posts/#{post.id}/room" %>
          <%= link_to  "レビュー", new_review_path(post.id) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div></div>
<div></div>